import React, { useState } from 'react';
import { View, Text, Pressable, StyleSheet, ScrollView, Linking, ActivityIndicator } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { colors } from '@/theme/colors';
import { api } from '@/api/client';
import { RootStackParamList } from '@/navigation/RootNavigator';

type Props = NativeStackScreenProps<RootStackParamList, 'MemoDetail'>;

const day = (iso: string | null) => (iso ? new Date(iso).toLocaleDateString() : '—');

export default function MemoDetailScreen({ route, navigation }: Props) {
  const { memo, engagement } = route.params;
  const [opening, setOpening] = useState(false);
  const [error, setError] = useState('');

  // GET /memos/{id}/pdf renders the PDF when asked and answers with a link to
  // it. The link is handed to the phone, which opens it in whatever views
  // PDFs; saving a copy is the viewer's to offer.
  const onOpen = async () => {
    setOpening(true);
    setError('');
    try {
      const { url } = await api.memoPdf(memo.memo_id);
      await Linking.openURL(url);
    } catch (err: any) {
      setError(err?.message || String(err));
    } finally {
      setOpening(false);
    }
  };

  return (
    <SafeAreaView style={styles.screen} edges={['top']}>
      <View style={styles.header}>
        <Pressable onPress={() => navigation.goBack()} hitSlop={10}>
          <Text style={styles.back}>{'‹'}</Text>
        </Pressable>
        <View style={{ flex: 1 }}>
          <Text style={styles.title} numberOfLines={1}>{memo.template_label}</Text>
          <Text style={styles.subtitle} numberOfLines={1}>
            {engagement} · Memo {memo.label}
          </Text>
        </View>
      </View>

      <ScrollView contentContainerStyle={{ padding: 20, gap: 16 }}>
        <View style={styles.card}>
          <Row label="Memo" value={memo.label} />
          <Row label="Revision" value={String(memo.revision)} />
          <Row label="Generated" value={day(memo.generated_at)} />
          <Row label="Generated by" value={memo.generated_by ?? '—'} />
          <Row label="Modified" value={day(memo.modified_at)} last />
        </View>
        {!!error && <Text style={styles.error}>{error}</Text>}
      </ScrollView>

      <View style={styles.actionBar}>
        <Pressable
          style={[styles.primaryBtn, opening && { opacity: 0.5 }]}
          disabled={opening}
          onPress={onOpen}
        >
          {opening ? <ActivityIndicator color={colors.surface} />
                   : <Text style={styles.primaryBtnText}>Open PDF</Text>}
        </Pressable>
      </View>
    </SafeAreaView>
  );
}

function Row({ label, value, last }: { label: string; value: string; last?: boolean }) {
  return (
    <View style={[styles.rowLine, !last && styles.rowLineBorder]}>
      <Text style={styles.rowLabel}>{label}</Text>
      <Text style={styles.rowValue} numberOfLines={1}>{value}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 12,
  },
  back: { fontSize: 28, color: colors.ink, width: 32, textAlign: 'center' },
  title: { fontSize: 17, fontWeight: '700', color: colors.ink },
  subtitle: { fontSize: 12.5, color: colors.subtext, marginTop: 1 },
  card: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
  },
  rowLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  rowLineBorder: { borderBottomWidth: 1, borderBottomColor: colors.border },
  rowLabel: { fontSize: 13.5, color: colors.subtext },
  rowValue: { flexShrink: 1, fontSize: 13.5, fontWeight: '600', color: colors.ink },
  error: { fontSize: 13.5, color: colors.ink },
  actionBar: {
    padding: 20,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  primaryBtn: {
    height: 50,
    borderRadius: 14,
    backgroundColor: colors.deep,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryBtnText: { color: colors.surface, fontSize: 16, fontWeight: '700' },
});
