#!/usr/bin/env python3
"""
load_pack.py - write the hard-coded pack into the registry as revision 1.

Every document filed so far was extracted against pack.py, and every stored
value references a field_key from it. So revision 1 must BE that pack, exactly:
if extraction against revision 1 does not reproduce what is already stored,
everything built on the registry is built on sand.

The pack is written to a reserved pack tenant and forked to each real tenant.
A fork is a deep copy, never a reference - later edits to a pack must not reach
a tenant who has already forked it.

Reads the live lambda/shared/pack.py and lambda/composition/template.py rather
than any copy, and emits SQL. Nothing here talks to the database: the output
goes through the same migration path as everything else, so what ran is
recorded and repeatable.

    python db/load_pack.py

Writes db/migrations/009_pack_revision_1.sql itself rather than printing to be
redirected: PowerShell's redirect writes UTF-16, which MySQL will not read.
"""

import importlib.util
import os
import sys

PACK_TENANT = 0            # reserved; not a real tenant
REAL_TENANTS = [1, 2]      # forked to these
REVISION = 1

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def load(path, name):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def q(value):
    """A SQL literal. Doubling the quote is the whole of the escaping, and it
    is enough: everything here is our own text, not a request."""
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return str(value)
    return "'" + str(value).replace("\\", "\\\\").replace("'", "''") + "'"


def main():
    pack = load(os.path.join(ROOT, "lambda", "shared", "pack.py"), "pack")
    template = load(os.path.join(ROOT, "lambda", "composition", "template.py"),
                    "template")

    # read_mode and always_ocr live in the textract module today, not the pack.
    try:
        textract = load(os.path.join(ROOT, "lambda", "shared", "textract.py"),
                        "textract")
        read_mode_for = textract.read_mode_for
        always_ocr = textract.always_ocr
    except Exception:
        def read_mode_for(_):
            return "text"

        def always_ocr(_):
            return False

    out = []
    w = out.append

    w("-- 009_pack_revision_1.sql")
    w("--")
    w("-- GENERATED by db/load_pack.py from the live pack.py and template.py.")
    w("-- Do not edit by hand: regenerate it.")
    w("--")
    w("-- The hard-coded pack, written into the registry as revision 1, so")
    w("-- that every document already filed still resolves and extraction")
    w("-- against revision 1 reproduces exactly what is stored today.")
    w("--")
    w("-- Written once to the reserved pack tenant (0) and forked to each real")
    w("-- tenant. A fork is a deep copy: later edits to a pack must never")
    w("-- reach a tenant who has already forked it.")
    w("")

    for tenant in [PACK_TENANT] + REAL_TENANTS:
        note = ("the built-in pack" if tenant == PACK_TENANT
                else "forked from the built-in pack")
        forked = None if tenant == PACK_TENANT else "pack:0:1"

        w("-- ---------------------------------------------------------------")
        w("-- tenant %d" % tenant)
        w("-- ---------------------------------------------------------------")
        w("")
        for table in ("config_section_field", "config_section",
                      "config_template", "config_field", "config_type_schema",
                      "config_schema", "config_document_type",
                      "config_category", "config_revision"):
            w("DELETE FROM %s WHERE tenant_id = %d AND revision = %d;"
              % (table, tenant, REVISION))
        w("")

        w("INSERT INTO config_revision")
        w("  (tenant_id, revision, status, forked_from, note, published_at,")
        w("   published_by)")
        w("VALUES (%d, %d, 'published', %s, %s, UTC_TIMESTAMP(), 'system');"
          % (tenant, REVISION, q(forked), q(note)))
        w("")

        # --- categories -----------------------------------------------------
        w("INSERT INTO config_category")
        w("  (tenant_id, revision, category_key, label, sort_order) VALUES")
        rows = ["  (%d, %d, %s, %s, %d)" % (tenant, REVISION, q(k), q(v), i)
                for i, (k, v) in enumerate(pack.CATEGORIES.items())]
        w(",\n".join(rows) + ";")
        w("")

        # --- document types -------------------------------------------------
        w("INSERT INTO config_document_type")
        w("  (tenant_id, revision, type_key, label, category_key, description,")
        w("   read_mode, always_ocr, sort_order) VALUES")
        rows = []
        for i, (key, spec) in enumerate(pack.DOCUMENT_TYPES.items()):
            rows.append("  (%d, %d, %s, %s, %s, %s, %s, %s, %d)" % (
                tenant, REVISION, q(key), q(spec["label"]),
                q(spec["category"]), q(spec["description"]),
                q(read_mode_for(key)), q(always_ocr(key)), i))
        w(",\n".join(rows) + ";")
        w("")

        # --- schemas --------------------------------------------------------
        w("INSERT INTO config_schema")
        w("  (tenant_id, revision, schema_key, label, instruction, sort_order)")
        w("VALUES")
        rows = []
        for i, (key, spec) in enumerate(pack.SCHEMAS.items()):
            rows.append("  (%d, %d, %s, %s, %s, %d)" % (
                tenant, REVISION, q(key), q(spec["label"]),
                q(spec.get("handler")), i))
        w(",\n".join(rows) + ";")
        w("")

        # --- the mapping ----------------------------------------------------
        w("INSERT INTO config_type_schema")
        w("  (tenant_id, revision, type_key, schema_key) VALUES")
        rows = []
        for key, spec in pack.DOCUMENT_TYPES.items():
            for schema_key in spec.get("schemas", []):
                rows.append("  (%d, %d, %s, %s)"
                            % (tenant, REVISION, q(key), q(schema_key)))
        w(",\n".join(rows) + ";")
        w("")

        # --- fields ---------------------------------------------------------
        # A group field becomes its columns, all sharing the group's key. That
        # shared key is what row_ordinal binds against, and it is what keeps
        # the third name attached to the third percentage. The group also
        # keeps a row of its own, carrying the label a renderer titles the
        # table with.
        w("INSERT INTO config_field")
        w("  (tenant_id, revision, schema_key, field_key, label, field_type,")
        w("   cardinality, description, group_key, sort_order) VALUES")
        rows = []
        order = 0
        for schema_key, spec in pack.SCHEMAS.items():
            for field in spec["fields"]:
                field_key, label, ftype, card, desc = field[:5]

                if card == "group":
                    for col in field[5]:
                        col_key, col_label, col_type, col_desc = col[:4]
                        rows.append(
                            "  (%d, %d, %s, %s, %s, %s, 'group', %s, %s, %d)"
                            % (tenant, REVISION, q(schema_key), q(col_key),
                               q(col_label), q(col_type), q(col_desc),
                               q(field_key), order))
                        order += 1
                    rows.append(
                        "  (%d, %d, %s, %s, %s, 'group', 'group', %s, %s, %d)"
                        % (tenant, REVISION, q(schema_key), q(field_key),
                           q(label), q(desc), q(field_key), order))
                    order += 1
                    continue

                rows.append("  (%d, %d, %s, %s, %s, %s, %s, %s, NULL, %d)" % (
                    tenant, REVISION, q(schema_key), q(field_key), q(label),
                    q(ftype), q(card), q(desc), order))
                order += 1
        w(",\n".join(rows) + ";")
        w("")

        # --- template -------------------------------------------------------
        w("INSERT INTO config_template")
        w("  (tenant_id, revision, template_key, label)")
        w("VALUES (%d, %d, %s, 'Due Diligence Memorandum');"
          % (tenant, REVISION, q(template.TEMPLATE_KEY)))
        w("")

        w("INSERT INTO config_section")
        w("  (tenant_id, revision, template_key, section_key, numeral, title,")
        w("   kind, shape_key, prompt, context_sections, sort_order) VALUES")
        rows = []
        for i, section in enumerate(template.MEMO_SECTIONS):
            context = section.get("context_sections") or []
            rows.append("  (%d, %d, %s, %s, %s, %s, %s, %s, %s, %s, %d)" % (
                tenant, REVISION, q(template.TEMPLATE_KEY),
                q(section["key"]), q(section["num"]), q(section["title"]),
                q(section["kind"]),
                # The consolidation's presentation directives are keyed on the
                # section key today, so revision 1 carries that unchanged.
                q(section["key"]),
                q(section.get("prompt")),
                q(",".join(context) if context else None), i))
        w(",\n".join(rows) + ";")
        w("")

        w("INSERT INTO config_section_field")
        w("  (tenant_id, revision, template_key, section_key, field_key,")
        w("   sort_order) VALUES")
        rows = []
        for section in template.MEMO_SECTIONS:
            for i, field_key in enumerate(section.get("fields") or []):
                rows.append("  (%d, %d, %s, %s, %s, %d)" % (
                    tenant, REVISION, q(template.TEMPLATE_KEY),
                    q(section["key"]), q(field_key), i))
        w(",\n".join(rows) + ";")
        w("")

    w("-- Point existing tenants at the revision they have in fact been using")
    w("-- all along.")
    for tenant in REAL_TENANTS:
        w("UPDATE tenant SET active_revision = %d WHERE tenant_id = %d;"
          % (REVISION, tenant))
    w("")

    target = os.path.join(HERE, "migrations", "009_pack_revision_1.sql")
    with open(target, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(out) + "\n")

    sys.stderr.write(
        "wrote %s\n  %d categories, %d types, %d schemas, %d fields, "
        "%d sections\n" % (
            target, len(pack.CATEGORIES), len(pack.DOCUMENT_TYPES),
            len(pack.SCHEMAS),
            sum((len(f[5]) + 1) if f[3] == "group" else 1
                for sc in pack.SCHEMAS.values() for f in sc["fields"]),
            len(template.MEMO_SECTIONS)))


if __name__ == "__main__":
    main()
